# Generated by Django 5.2.7 on 2025-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('sku', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
